/**
 * QUOI     — ce que la page /da doit montrer : les couleurs des jetons et les briques.
 * POURQUOI — deux tests comparent ces listes à la réalité (tokens.css, dossier shared/ui) :
 *            rien ne peut exister sans apparaître sur la page.
 */
export const COLOR_TOKENS = [
  '--color-fond',
  '--color-surface',
  '--color-barre',
  '--color-sable',
  '--color-bord',
  '--color-encre',
  '--color-texte',
  '--color-texte-doux',
  '--color-texte-pale',
  '--color-sur-accent',
  '--color-accent',
  '--color-accent-clair',
  '--color-onglet',
  '--color-onglet-ferme',
  '--color-rose',
  '--color-ocre',
  '--color-kaki',
  '--color-vert',
  '--color-lien',
  '--color-succes',
  '--color-succes-fond',
  '--color-pastille',
  '--color-choisie',
  '--color-vignette',
  '--color-brun',
  '--color-doux-fond',
  '--color-feuille',
  '--color-ombre',
  '--color-desactive-fond',
  '--color-desactive-bord',
  '--color-desactive-texte',
  '--color-carte-fond',
  '--color-carte-eau',
  '--color-carte-route',
  '--color-carte-encre',
  '--color-carte-halo',
  '--color-carte-foret',
  '--color-carte-ombre',
  '--color-carte-cire',
  '--color-fiche-titre',
  '--color-fiche-ligne',
  '--color-fiche-aide',
  '--color-fiche-recit',
  '--color-fiche-badge',
  '--color-fiche-badge-texte',
  '--color-fiche-fleche',
  '--color-fiche-credit',
  '--color-fiche-credit-texte',
  '--color-fiche-credit-pale',
  '--color-fiche-rond',
  '--color-fiche-vignette',
  '--color-fiche-lisiere',
  '--color-accent-bord',
  '--color-pilule',
  '--color-pilule-texte',
  '--color-voile',
  '--color-voile-bord',
  '--color-dechirure',
  '--color-confetti-or',
  '--color-confetti-vert',
  '--color-canal-bugs',
  '--color-canal-bugs-texte',
  '--color-canal-activite',
  '--color-canal-activite-texte',
  '--color-ajoute',
  '--color-retire',
] as const

export const DA_SHOWCASED = [
  'Avatar',
  'BilleType',
  'Button',
  'Champ',
  'ChoixDuCalendrier',
  'EmptyState',
  'Envols',
  'Feuille',
  'FeuilleDeSignalement',
  'IconButton',
  'Interrupteur',
  'LieuCarte',
  'Pastille',
  'PastilleChoix',
  'PlanSatellite',
  'Recompense',
  'Segments',
  'Text',
] as const

export const SPACE_TOKENS = [
  '--space-1',
  '--space-2',
  '--space-3',
  '--space-4',
  '--space-6',
  '--space-8',
] as const

export const RADIUS_TOKENS = [
  '--radius-vignette',
  '--radius-petit',
  '--radius',
  '--radius-carte',
  '--radius-feuille',
  '--radius-rond',
] as const
