-- Énigmes quotidiennes — difficulté "easy" — ~55 entrées réparties sur 4 factions
-- Générées le 2026-04-07

INSERT INTO enigmas (type, difficulty, heritage_id, format, question, lore_text, choices, answer, explanation, active) VALUES

-- =============================================
-- FACTION CELTIQUE (14)
-- =============================================

('daily', 'easy', 'faction-celtique', 'qcm',
 'Quel était le nom des prêtres et savants celtes qui officiaient lors des rituels et transmettaient la mémoire du peuple ?',
 'Sous les frondaisons sacrées du chêne, des hommes vêtus de blanc cueillaient le gui à la faucille d''or…',
 '["Les Druides", "Les Augures", "Les Bardes", "Les Ovates"]',
 'Les Druides',
 'Les Druides formaient la classe sacerdotale et intellectuelle des sociétés celtes. Ils étaient à la fois prêtres, juges, philosophes et enseignants. César les décrit comme exemptés de service militaire et de taxes.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Comment s''appelait le chef gaulois qui mena la grande révolte contre César en 52 av. J.-C. ?',
 'De la forteresse d''Alésia, un cri de guerre traversa les collines — et l''histoire retint son nom pour toujours.',
 '["Vercingétorix", "Ambiorix", "Viriatus", "Dumnorix"]',
 'Vercingétorix',
 'Vercingétorix, chef des Arvernes, fédéra les tribus gauloises contre Rome et remporta la bataille de Gergovie. Vaincu à Alésia, il fut emmené à Rome et exécuté six ans plus tard.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Quel arbre était considéré comme sacré par les Celtes et donnait son nom à leurs lieux de culte ?',
 'Ses racines plongent aussi profond que ses branches s''élèvent — il est le pilier entre les trois mondes.',
 '["Le Chêne", "Le Frêne", "L''If", "Le Bouleau"]',
 'Le Chêne',
 'Le mot "druide" est probablement dérivé du proto-celtique *dru-wid, où *dru signifie chêne (ou "solide"). Le gui poussant sur le chêne était particulièrement vénéré lors des rites de cueillette.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'En quel siècle les Gaulois ont-ils saccagé Rome pour la première fois ?',
 'Les oies du Capitole criaient dans la nuit — mais les soldats romains dormaient, et les Gaulois montaient en silence.',
 '["IVe siècle av. J.-C.", "IIe siècle av. J.-C.", "IIIe siècle av. J.-C.", "Ve siècle av. J.-C."]',
 'IVe siècle av. J.-C.',
 'En 390 av. J.-C. (IVe siècle), les Gaulois Sénons commandés par Brennus défont l''armée romaine à la Allia, puis pillent Rome. La phrase attribuée à Brennus, "Vae victis !" (malheur aux vaincus !), est restée célèbre.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Comment s''appelait le dieu gaulois souvent associé au soleil et représenté avec une roue ?',
 'La roue tourne, le soleil avance — et le dieu du ciel lance ses rayons comme autant de rayons de char.',
 '["Taranis", "Cernunnos", "Lugh", "Ogmios"]',
 'Taranis',
 'Taranis était le dieu du tonnerre et du ciel chez les Gaulois. Son attribut principal était la roue solaire, symbole du cycle cosmique. Il formait avec Esus et Toutatis une triade divine mentionnée par Lucain.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Quel dieu celte cornu est souvent représenté assis en tailleur, entouré d''animaux sauvages ?',
 'Au creux de la forêt primordiale, entre le cerf et le serpent, siège le maître des bêtes et des passages.',
 '["Cernunnos", "Taranis", "Esus", "Sucellus"]',
 'Cernunnos',
 'Cernunnos est le dieu aux bois de cerf, maître des animaux et du monde sauvage. Il est représenté sur le chaudron de Gundestrup. Son nom même signifie probablement "le cornu" en gaulois.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Quelle est la grande forteresse gauloise où Vercingétorix fut finalement vaincu par César ?',
 'Les fossés s''étiraient sur des kilomètres, et deux armées gauloises ne purent briser l''étau romain.',
 '["Alésia", "Gergovie", "Bibracte", "Uxellodunum"]',
 'Alésia',
 'Le siège d''Alésia (52 av. J.-C.) est un chef-d''œuvre de génie militaire romain. César fit construire deux lignes de fortifications (contrevallation et circonvallation) pour piéger Vercingétorix tout en repoussant une armée de secours.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Quelle tribu gauloise habitait autour de l''actuelle Paris, donnant son nom à la ville ?',
 'Sur l''île de la Seine, leurs bateaux glissaient, et leur nom resta gravé dans la pierre des siècles.',
 '["Les Parisii", "Les Carnutes", "Les Éduens", "Les Arvernes"]',
 'Les Parisii',
 'Les Parisii étaient une tribu gauloise établie sur l''île de la Cité et les rives de la Seine. Leur oppidum Lutetia est à l''origine de Paris. Leur emblème, la barque, figure encore sur les armoiries de Paris.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Quel métal, rare et précieux, les artisans celtes maîtrisaient-ils pour fabriquer bijoux et torques ?',
 'Le métal jaune coulait sous les doigts des orfèvres, prenant la forme de spirales et de nœuds sacrés.',
 '["L''or", "Le bronze", "L''étain", "Le fer"]',
 'L''or',
 'Les orfèvres celtes étaient réputés dans tout le monde antique pour leur maîtrise de l''or. Le torque (collier rigide en or torsadé) était le signe de haut rang par excellence. De nombreux trésors celtes en or ont été retrouvés en France et en Irlande.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'En quelle langue les inscriptions gauloises étaient-elles rédigées, avant l''adoption du latin ?',
 'Les lettres tracées sur la pierre ou le bois portaient les formules des hommes d''avant — avant que Rome n''écrive sur tout.',
 '["En alphabet grec ou latin adapté au gaulois", "En runique", "En phénicien", "En étrusque"]',
 'En alphabet grec ou latin adapté au gaulois',
 'Les Gaulois du Midi utilisaient d''abord l''alphabet grec de Marseille pour écrire leur langue, avant d''adopter l''alphabet latin. La langue gauloise appartenait à la famille des langues celtiques continentales.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Quel festin mythique irlandais réunit les héros de l''Autre Monde autour d''un chaudron d''abondance ?',
 'La corne d''abondance ne se vide jamais pour les braves — tel est le pacte de l''Autre Monde avec les vivants.',
 '["Le festin de Bricriu", "Le Graal celtique", "L''assemblée de Tara", "Le banquet de Finn"]',
 'Le festin de Bricriu',
 'Le Festin de Bricriu est l''un des grands textes de la mythologie irlandaise du Cycle d''Ulster. Bricriu le "venimeux" organise un banquet pour provoquer les héros — dont Cú Chulainn — à se disputer le "morceau du champion".',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Quel héros irlandais du Cycle d''Ulster était connu pour ses exploits surhumains et sa mort tragique ?',
 'Sa naissance fut présage de gloire et de mort — et il choisit une vie brève mais lumineuse plutôt qu''une longue obscurité.',
 '["Cú Chulainn", "Finn Mac Cool", "Diarmuid", "Conall Cernach"]',
 'Cú Chulainn',
 'Cú Chulainn (le chien de Culann) est le grand héros du Cycle d''Ulster. Fils du dieu Lugh, il accomplit des exploits extraordinaires dans un état de fureur guerrière appelé le "riastrad". Il mourut jeune, conformément à la prophétie.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Quelle cérémonie celte marquait le début de l''année au 1er novembre et est à l''origine d''Halloween ?',
 'La nuit où les frontières entre les vivants et les morts s''amincissent jusqu''à disparaître — les ancêtres reviennent festoyer.',
 '["Samain", "Beltaine", "Imbolc", "Lughnasadh"]',
 'Samain',
 'Samain (ou Samhain) était la fête celte du Nouvel An, célébrée dans la nuit du 31 octobre au 1er novembre. C''était un moment de passage entre les mondes. Les Chrétiens la transformèrent en Toussaint, et ses pratiques populaires donnèrent Halloween.',
 true),

('daily', 'easy', 'faction-celtique', 'qcm',
 'Comment appelle-t-on les grandes enceintes fortifiées collinaires que les Gaulois utilisaient comme villes et centres politiques ?',
 'Sur les hauteurs, derrière les remparts de bois et de pierre, bat le cœur d''une tribu tout entière.',
 '["Des oppida", "Des villas", "Des castella", "Des castra"]',
 'Des oppida',
 'Les oppida (singulier : oppidum) étaient de vastes agglomérations fortifiées gauloises construites sur des hauteurs. Bibracte, Gergovie et Alésia en sont des exemples célèbres. César en décrit de nombreux dans la Guerre des Gaules.',
 true),

-- =============================================
-- FACTION NORDIQUE (14)
-- =============================================

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quel est le nom du marteau du dieu nordique Thor, symbole de sa puissance sur la foudre ?',
 'Forgé par les nains dans les profondeurs de la terre, il revient toujours dans la main qui le lance.',
 '["Mjöllnir", "Gungnir", "Gram", "Tyrfing"]',
 'Mjöllnir',
 'Mjöllnir, le marteau de Thor, est l''arme la plus célèbre de la mythologie nordique. Son nom signifie probablement "broyeur". Il est si lourd que seul Thor peut le porter, et il revient toujours dans sa main après avoir été lancé.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Comment s''appelle le palais céleste d''Odin où vont les guerriers morts au combat ?',
 'Les Valkyries choisissent les braves sur les champs de bataille — et les conduisent vers les murs d''or.',
 '["Le Valhalla", "L''Asgard", "Le Midgard", "Niflheim"]',
 'Le Valhalla',
 'Le Valhalla (Valhöll, "salle des tués") est la grande salle d''Odin en Asgard. Les einherjar (guerriers élus) y festoient et s''entraînent chaque jour jusqu''au Ragnarök. Seuls les guerriers morts au combat pouvaient y être admis.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quel est le nom du grand frêne cosmique qui soutient les neuf mondes de la cosmologie nordique ?',
 'Ses racines plongent dans les puits du destin, de la sagesse et du Niflheim — et ses branches portent tout ce qui existe.',
 '["Yggdrasil", "Mjöllnir", "Bifröst", "Urðarbrunnr"]',
 'Yggdrasil',
 'Yggdrasil est le frêne cosmique de la mythologie nordique. Son nom signifie "le destrier d''Ygg (Odin)", en référence au sacrifice d''Odin pendu à l''arbre pour découvrir les runes. Ses trois racines plongent vers Asgard, Jötunheim et Niflheim.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quel dieu nordique est le dieu de la ruse, du feu et du chaos, fils adoptif d''Odin ?',
 'Il riait quand les autres pleuraient, et pleurait quand les autres riaient — jamais on ne sut de quel côté il se rangerait.',
 '["Loki", "Tyr", "Baldr", "Heimdall"]',
 'Loki',
 'Loki est le dieu de la ruse (trickster) de la mythologie nordique. D''abord allié des Ases, il devient de plus en plus malveillant. Il est responsable de la mort de Baldr et sera enchaîné jusqu''au Ragnarök, où il se battra du côté des géants.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'En quel siècle les Vikings commencèrent-ils leurs grandes expéditions en Europe occidentale ?',
 'Des drakkars surgirent de la brume, et les moines de Lindisfarne comprirent que le monde avait changé.',
 '["VIIIe siècle", "VIe siècle", "IXe siècle", "Xe siècle"]',
 'VIIIe siècle',
 'Le raid sur le monastère de Lindisfarne en 793 marque traditionnellement le début de l''Âge Viking. Cette date du VIIIe siècle inaugure deux siècles d''expansion scandinave vers l''Irlande, la France, la Russie et même l''Amérique du Nord.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quel chef viking donna son nom à la Normandie après s''y être installé au Xe siècle ?',
 'Le roi des Francs lui céda la terre pour acheter la paix — et le Nord s''installa dans le cœur de la Gaule.',
 '["Rollon", "Ragnar Lothbrok", "Harald à la Belle Chevelure", "Sigurd le Serpent de l''Œil"]',
 'Rollon',
 'Rollon (ou Hrólf) fut le premier duc de Normandie. En 911, par le traité de Saint-Clair-sur-Epte, Charles le Simple lui céda le territoire en échange de sa conversion au christianisme et de sa protection contre d''autres raids vikings.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Comment appelle-t-on les femmes guerrières ou esprits féminins qui choisissaient les morts sur les champs de bataille nordiques ?',
 'Elles planaient au-dessus des mourants, invisibles mais implacables — désignant ceux qui iraient festoyer avec Odin.',
 '["Les Valkyries", "Les Nornes", "Les Disir", "Les Shieldmaidens"]',
 'Les Valkyries',
 'Les Valkyries (valkyrja, "celle qui choisit les tués") étaient les servantes d''Odin chargées de sélectionner les guerriers dignes d''entrer au Valhalla. Parmi les plus connues : Brynhildr et Sigrun. Elles chevauchaient des chevaux et portaient des lances.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quel est le nom du pont arc-en-ciel reliant le monde des hommes (Midgard) à celui des dieux (Asgard) ?',
 'Il brille de mille couleurs entre les royaumes — et seuls les dieux et les élus peuvent le traverser.',
 '["Bifröst", "Yggdrasil", "Gjöll", "Ginnungagap"]',
 'Bifröst',
 'Le Bifröst est le pont arc-en-ciel de la mythologie nordique, gardé par Heimdall. Il sera détruit lors du Ragnarök quand les géants de feu (fils de Surtr) le traverseront en masse pour attaquer Asgard.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quel type de bateau les Vikings utilisaient-ils pour leurs raids côtiers, rapide et capable de naviguer en eaux peu profondes ?',
 'La tête de dragon à la proue regardait l''horizon — et les hommes à bord ramaient comme si leur vie en dépendait.',
 '["Le drakkar", "Le knarr", "La galère", "Le cog"]',
 'Le drakkar',
 'Le drakkar (longship en anglais) était le navire de guerre viking par excellence. Avec son tirant d''eau très faible, il pouvait remonter les rivières et s''échouer sur les plages. Le knarr était le navire de commerce plus large et moins rapide.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quel dieu nordique perdit sa main droite en la sacrifiant pour enchaîner le loup Fenrir ?',
 'Il tendit la main dans la gueule du loup pour que les autres dieux puissent ligoter la bête — sachant ce qu''il perdrait.',
 '["Tyr", "Odin", "Thor", "Freyr"]',
 'Tyr',
 'Tyr, dieu de la justice et du combat singulier, offrit sa main droite comme garantie au loup Fenrir pendant que les autres dieux l''enchaînaient avec le lien magique Gleipnir. Son sacrifice permit de retarder le Ragnarök.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quelle est la fin du monde dans la cosmologie nordique, la bataille ultime des dieux contre les géants et les monstres ?',
 'Les loups avaleront le soleil et la lune, Yggdrasil tremblera — et les dieux mourront en combattant, sachant qu''ils mourront.',
 '["Le Ragnarök", "Le Fimbulwinter", "Le Niflheim", "La Wyrd"]',
 'Le Ragnarök',
 'Le Ragnarök ("destin des dieux") est la grande apocalypse nordique. Odin mourra avalé par Fenrir, Thor sera tué par le Serpent du Midgard, Freyr tombera face à Surtr. Mais un nouveau monde renaîtra ensuite, plus pur.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quel explorateur viking est considéré comme le premier Européen à avoir atteint l''Amérique du Nord, vers l''an 1000 ?',
 'Au-delà de toutes les cartes connues, il vogua vers l''ouest — et trouva une terre que personne n''avait encore nommée.',
 '["Leif Erikson", "Erik le Rouge", "Bjarne Herjolfsson", "Thorvald Erikson"]',
 'Leif Erikson',
 'Leif Erikson, fils d''Erik le Rouge, atteignit le Vinland (probablement Terre-Neuve) vers l''an 1000. Le site archéologique de L''Anse aux Meadows au Canada confirme la présence viking en Amérique du Nord, 500 ans avant Colomb.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Comment s''appelle le système d''écriture utilisé par les peuples germaniques et nordiques, aux caractères anguleux taillés dans le bois ou la pierre ?',
 'Chaque signe porte une force propre — graver une rune, c''est convoquer quelque chose d''ancien et de puissant.',
 '["Les runes", "Les glyphes", "L''ogham", "Les cunéiformes"]',
 'Les runes',
 'Les runes sont le système d''écriture des peuples germaniques (alphabet futhark). L''Elder Futhark (Ier-VIIe siècle) comporte 24 signes. Au-delà de leur usage pratique, les runes avaient une dimension magique et divinatoire.',
 true),

('daily', 'easy', 'faction-nordique', 'qcm',
 'Quelle est la capitale légendaire d''Asgard, résidence principale d''Odin dans la mythologie nordique ?',
 'Au sommet du monde des dieux, entouré de murailles forgées par les géants, se dresse le trône du Père de Tout.',
 '["Glaðsheim / Valaskjálf", "Valhalla", "Ýdalir", "Fólkvangr"]',
 'Glaðsheim / Valaskjálf',
 'Valaskjálf est le palais d''Odin dans Asgard, où se trouve son trône Hliðskjálf depuis lequel il observe les neuf mondes. Glaðsheim est la grande salle où siègent les douze dieux Ases lors de leurs assemblées.',
 true),

-- =============================================
-- FACTION ROMAINE (14)
-- =============================================

('daily', 'easy', 'faction-romaine', 'qcm',
 'Selon la tradition, en quelle année Rome fut-elle fondée ?',
 'Deux jumeaux nourris par une louve, une cité tracée au soc d''une charrue — ainsi naquit l''Éternelle.',
 '["753 av. J.-C.", "509 av. J.-C.", "264 av. J.-C.", "44 av. J.-C."]',
 '753 av. J.-C.',
 'La fondation de Rome par Romulus est traditionnellement datée de 753 av. J.-C. (anno urbis conditae). Cette date, calculée par l''annaliste Varron, servait de référence au calendrier romain. Archéologiquement, des traces d''occupation du Palatin remontent au VIIIe siècle av. J.-C.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Quel est le nom de la déesse romaine de la sagesse, des arts et de la guerre stratégique, équivalente à Athéna ?',
 'Son temple dominait le Capitole — non pas en déesse de guerre, mais en gardienne de la cité et des savoirs.',
 '["Minerve", "Junon", "Diane", "Vénus"]',
 'Minerve',
 'Minerve était l''une des trois divinités de la Triade Capitoline avec Jupiter et Junon. Déesse de la sagesse, des arts et des techniques de guerre, elle était particulièrement vénérée des artisans, des médecins et des poètes.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Comment s''appelait l''assemblée de citoyens romains qui votait les lois et élisait les magistrats sous la République ?',
 'Dans le Forum, les voix des citoyens s''élevaient — et les décisions de la cité se prenaient en plein air.',
 '["Le Sénat", "Les Comices", "Le Concile de la Plèbe", "Le Tribunal"]',
 'Le Sénat',
 'Sous la République romaine, le Sénat (Senatus) était l''organe principal de gouvernement, composé d''anciens magistrats. Il contrôlait les finances, la politique étrangère et les provinces. Les comices votaient les lois mais le Sénat restait prédominant.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Quel type de construction romaine permettait de transporter l''eau sur de longues distances grâce à un écoulement par gravité ?',
 'Des arches de pierre s''étirent à perte de vue — et l''eau coule sans pompe ni machine, portée par la seule pente.',
 '["L''aqueduc", "Le cloaque", "Le castellum", "L''hypocauste"]',
 'L''aqueduc',
 'Les aqueducs romains sont l''une des plus grandes réalisations d''ingénierie de l''Antiquité. Rome comptait onze aqueducs principaux approvisionnant la ville en eau. Le Pont du Gard (France) est l''un des mieux conservés, avec une dénivellation de seulement 17 mètres sur 50 km.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Quel était le nom du plus grand amphithéâtre romain, construit à Rome sous les Flaviens et pouvant accueillir 50 000 spectateurs ?',
 'Ses arches encerclaient l''arène comme les bras d''un colosse — et le rugissement de la foule se mêlait au sang sur le sable.',
 '["Le Colisée (Amphithéâtre Flavien)", "Le Circus Maximus", "Le Panthéon", "Le Forum de Trajan"]',
 'Le Colisée (Amphithéâtre Flavien)',
 'Le Colisée (Amphitheatrum Flavium) fut construit entre 70 et 80 apr. J.-C. sous les empereurs Vespasien et Titus. Il pouvait accueillir entre 50 000 et 80 000 spectateurs pour les combats de gladiateurs, les chasses aux animaux et les exécutions publiques.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Quel général romain traversa les Alpes avec des éléphants pour attaquer Rome par le nord au IIIe siècle av. J.-C. ?',
 'Les montagnes enneigées ne l''arrêtèrent pas — il descendit sur l''Italie comme une tempête venue du sud.',
 '["Hannibal Barca", "Pyrrhus d''Épire", "Mithridate", "Viriatus"]',
 'Hannibal Barca',
 'Hannibal Barca, général carthaginois, traversa les Alpes en 218 av. J.-C. avec 37 éléphants de guerre lors de la Deuxième Guerre Punique. Il infligea plusieurs défaites sévères à Rome (Tessin, Trébie, Lac Trasimène, Cannes) mais ne put jamais prendre la ville.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Combien de légions composait environ l''armée romaine à son apogée sous le Haut-Empire ?',
 'Chaque légion, une ville en marche — disciplinée, armée, prête à planter son aigle aux confins du monde connu.',
 '["Une trentaine de légions", "Dix légions", "Cent légions", "Cinq légions"]',
 'Une trentaine de légions',
 'Au Haut-Empire, Rome alignait entre 25 et 33 légions selon les périodes. Chaque légion comptait environ 5 000 à 6 000 hommes. L''aigle d''argent (aquila) était le symbole sacré de chaque légion — perdre son aigle était le pire déshonneur.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Quel mot latin désigne la grande place publique au cœur de chaque cité romaine, servant de marché et de lieu politique ?',
 'Sous les colonnes du temple, dans la rumeur du marché et l''éclat des plaidoiries, battait le cœur de toute cité.',
 '["Forum", "Basilique", "Capitole", "Curia"]',
 'Forum',
 'Le forum était le centre civique, commercial et religieux de toute ville romaine. Le Forum Romanum à Rome en était le modèle. Chaque cité de province avait son propre forum reproduisant ce modèle, signe visible de la romanisation.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Quel empereurroma romain fit construire un mur défensif en Bretagne (actuelle Angleterre) pour marquer la frontière nord de l''Empire ?',
 'Une ligne de pierre et de tourbes traversait l''île d''un bout à l''autre — derrière elle, la civilisation ; devant, l''inconnu.',
 '["Hadrien", "Trajan", "Constantin", "Domitien"]',
 'Hadrien',
 'Le mur d''Hadrien fut construit à partir de 122 apr. J.-C. sur ordre de l''empereur Hadrien. Long de 117 km, il traversait l''Angleterre de la mer du Nord à la mer d''Irlande. Il marquait la limite nord-ouest de l''Empire romain.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Quel est le nom du système de chauffage par le sol utilisé dans les thermes et villas romaines, où l''air chaud circulait sous les dalles ?',
 'Sous les mosaïques, un souffle chaud monte des entrailles de la maison — le confort romain, invisible mais omniprésent.',
 '["L''hypocauste", "Le caldarium", "Le tepidarium", "L''apodyterium"]',
 'L''hypocauste',
 'L''hypocauste (hypocaustum) était un système de chauffage romain par le sol, inventé au Ier siècle av. J.-C. Des pilettes de briques (pilae) surélevaient le plancher, permettant à l''air chaud produit par un foyer (praefurnium) de circuler en dessous.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Comment les Romains nommaient-ils leur dieu suprême, maître du tonnerre et des autres dieux ?',
 'Son aigle plongeait sur les armées ennemies — et son éclair annonçait que la faveur divine avait changé de camp.',
 '["Jupiter", "Mars", "Saturn", "Pluton"]',
 'Jupiter',
 'Jupiter (Iuppiter, contraction de Iovis Pater, "Père du ciel") était le dieu suprême du panthéon romain. Équivalent de Zeus grec, il était le protecteur de Rome et de son Empire. Son temple sur le Capitole était le plus sacré de la ville.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'En quel siècle l''Empire romain d''Occident prit-il fin officiellement ?',
 'Les aigles se posèrent, les légions rentrèrent leurs étendards — et mille ans d''histoire s''arrêtèrent en un seul jour.',
 '["Ve siècle apr. J.-C.", "IVe siècle apr. J.-C.", "VIe siècle apr. J.-C.", "IIIe siècle apr. J.-C."]',
 'Ve siècle apr. J.-C.',
 'L''Empire romain d''Occident prit fin en 476 apr. J.-C. (Ve siècle) quand Odoacre, chef barbare, déposa le dernier empereur Romulus Augustule. Cette date marque conventionnellement la fin de l''Antiquité et le début du Moyen Âge.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Quel bâtiment romain, recouvert d''un dôme remarquable, est dédié à "tous les dieux" et est encore debout à Rome ?',
 'Son dôme parfait n''a pas de fenêtres — juste un œil ouvert sur le ciel, l''oculus par lequel entre la lumière divine.',
 '["Le Panthéon", "Le Colisée", "Les Thermes de Caracalla", "La Basilique de Maxence"]',
 'Le Panthéon',
 'Le Panthéon de Rome fut construit sous Hadrien vers 125 apr. J.-C. Son dôme en béton de 43 mètres de diamètre reste le plus grand dôme non renforcé du monde. L''oculus (ouverture de 8,7 m) au sommet est la seule source de lumière.',
 true),

('daily', 'easy', 'faction-romaine', 'qcm',
 'Quel célèbre traité d''art militaire romain, rédigé au IVe siècle, reste une référence sur l''organisation des légions ?',
 'Sur parchemin, un officier consigna les secrets de la légion victorieuse — et ses pages traversèrent les siècles.',
 '["L''Epitoma rei militaris de Végèce", "La Guerre des Gaules de César", "L''Art de la guerre de Sun Tzu", "Les Stratégèmes de Frontin"]',
 'L''Epitoma rei militaris de Végèce',
 'L''Epitoma rei militaris (ou De re militari) de Flavius Végèce Renatus, rédigé fin IVe siècle, est le principal traité militaire romain conservé. Il décrit l''organisation, l''entraînement et les tactiques des légions, et fut étudié tout au long du Moyen Âge.',
 true),

-- =============================================
-- FACTION BYZANTINE (13)
-- =============================================

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quel était le nom de la capitale de l''Empire byzantin, fondée par Constantin Ier sur le Bosphore ?',
 'Entre deux continents, la ville aux sept collines portait la lumière d''un empire qui refusait de mourir.',
 '["Constantinople", "Antioche", "Thessalonique", "Alexandrie"]',
 'Constantinople',
 'Constantinople (aujourd''hui Istanbul) fut fondée par Constantin Ier en 330 apr. J.-C. sur le site de l''ancienne Byzance. Elle fut la capitale de l''Empire romain d''Orient puis byzantin pendant plus de mille ans, jusqu''à sa chute en 1453.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quel est le nom de la grande église de Constantinople, chef-d''œuvre de l''architecture byzantine construite au VIe siècle ?',
 'Son dôme semblait suspendu par des chaînes d''or invisibles — les fidèles croyaient que les anges le maintenaient en l''air.',
 '["Sainte-Sophie (Hagia Sophia)", "Le Palais des Blachernes", "L''église des Saints-Apôtres", "Sainte-Irène"]',
 'Sainte-Sophie (Hagia Sophia)',
 'Sainte-Sophie (Hagia Sophia, "Sainte Sagesse") fut construite sous Justinien Ier et inaugurée en 537. Son immense dôme de 31 mètres de diamètre, qui semble flotter grâce à ses fenêtres à la base, révolutionna l''architecture. Elle fut cathédrale, puis mosquée, puis musée.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quel emperor byzantin rédigea le Code Justinien, une compilation monumentale du droit romain toujours influente aujourd''hui ?',
 'Il voulut que les lois de Rome survivent à Rome elle-même — et fit graver en latin ce que les Grecs administreraient.',
 '["Justinien Ier", "Constantin Ier", "Héraclius", "Basile II"]',
 'Justinien Ier',
 'Justinien Ier (527-565) fit compiler le Corpus Juris Civilis sous la direction du juriste Tribonien. Ce code, achevé en 534, rassemblait des siècles de droit romain. Il fonde encore aujourd''hui les systèmes juridiques de nombreux pays européens.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quelle arme secrète les Byzantins utilisaient-ils pour incendier les flottes ennemies, et dont la composition resta mystérieuse ?',
 'Les navires ennemis brûlèrent sur l''eau — et même les vagues semblaient nourrir ces flammes que rien n''éteignait.',
 '["Le feu grégeois", "La baliste à pétrole", "Le siphon à naphte", "Les grenades à soufre"]',
 'Le feu grégeois',
 'Le feu grégeois fut une arme redoutable de la flotte byzantine dès le VIIe siècle. Projeté par des siphons, il brûlait même sur l''eau. Sa composition exacte reste inconnue à ce jour, mais contenait probablement de la résine de pin, du naphte et de la chaux vive.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quel style artistique byzantin plaçait des figures hiératiques sur fond d''or, sans perspective, pour signifier le sacré hors du temps ?',
 'Sur le panneau de bois, le regard du saint ne vous regarde pas — il regarde au-delà, dans un espace que l''œil ne peut atteindre.',
 '["L''icône", "La mosaïque antique", "La fresque romaine", "L''enluminure carolingienne"]',
 'L''icône',
 'L''icône (eikōn, "image") est l''image sacrée de la théologie byzantine. Sa frontalité, l''absence de perspective et le fond d''or symbolisent la réalité divine hors du temps. La querelle de l''iconoclasme (VIIIe-IXe siècle) faillit détruire cette tradition.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'En quel siècle l''Empire byzantin prit-il fin avec la chute de Constantinople ?',
 'Le dernier empereur combattit jusqu''au bout dans la brèche — et le croissant remplaça la croix sur les coupoles.',
 '["XVe siècle", "XIIIe siècle", "XIVe siècle", "XVIe siècle"]',
 'XVe siècle',
 'Constantinople tomba le 29 mai 1453 (XVe siècle) face aux armées ottomanes de Mehmed II. Le dernier empereur, Constantin XI Paléologue, mourut au combat. Cette date marque conventionnellement la fin du Moyen Âge en Europe.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Comment s''appelait la garde d''élite de l''Empereuromain byzantin, composée de guerriers étrangers dont de nombreux Vikings ?',
 'Ces hommes du Nord portaient leurs haches danoises au service d''un Dieu et d''un Basileus qu''ils avaient choisi librement.',
 '["La Garde Varègue", "La Tagmata", "Les Cataphractoi", "Les Stratiotai"]',
 'La Garde Varègue',
 'La Garde Varègue (Variagoi en grec) fut créée à la fin du Xe siècle. Composée d''abord de guerriers Rus et Vikings, puis d''Anglais après 1066, elle était la garde personnelle de l''Empereur. Les Varègues étaient réputés pour leur loyauté absolue et leur redoutable habileté au combat.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quel patriarche de Constantinople créa au IXe siècle un alphabet pour écrire les langues slaves, ancêtre de l''alphabet cyrillique ?',
 'Pour que l''Évangile parle en toutes langues, il fallut d''abord inventer les lettres qui les porteraient.',
 '["Cyrille (et Méthode)", "Photios", "Jean Chrysostome", "Basile de Césarée"]',
 'Cyrille (et Méthode)',
 'Saints Cyrille et Méthode, deux frères de Thessalonique, créèrent au IXe siècle l''alphabet glagolitique pour transcrire la langue slavonne liturgique. L''alphabet cyrillique, qui en dérive, fut nommé en l''honneur de Cyrille et est toujours utilisé en Russie, Bulgarie et Serbie.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quel terme grec désigne l''Empereuromain byzantin, littéralement "roi des rois" dans la tradition orientale ?',
 'Il ne se disait pas "Imperator" — il portait un titre plus ancien, plus chargé, héritage des monarques d''Orient.',
 '["Basileus", "Autocrator", "Despote", "Sebastokrator"]',
 'Basileus',
 'Basileus (roi en grec) devint le titre officiel des Empereurs byzantins à partir d''Héraclius (610-641), remplaçant le latin Imperator. Le titre complet "Basileus ton Rhomaion" (Roi des Romains) soulignait la continuité avec l''Empire romain.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quel symbole, combinant les lettres grecques X (Chi) et P (Rho), fut adopté par Constantin comme signe chrétien impérial ?',
 'La vision d''avant la bataille avait été claire : sous ce signe, tu vaincras — et l''Empire changea de dieux.',
 '["Le Chrismon (☧)", "La croix latine", "L''alpha et l''oméga", "L''ichthus"]',
 'Le Chrismon (☧)',
 'Le Chrismon ou Chi-Rho est formé des deux premières lettres du mot grec Christos. Constantin l''adopta comme symbole après sa vision avant la bataille du Pont Milvius (312). C''est l''un des premiers symboles chrétiens utilisés officiellement par un pouvoir impérial.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quel est le nom du grand hippodrome de Constantinople où se déroulaient les courses de chars et les célébrations impériales ?',
 'Dans l''arène aux cent mille voix, la couleur de votre faction valait plus que votre nom ou votre sang.',
 '["L''Hippodrome de Constantinople", "Le Circus Maximus de Byzance", "Le Stade de Théodose", "L''Arène des Bleus"]',
 'L''Hippodrome de Constantinople',
 'L''Hippodrome de Constantinople, construit par Septime Sévère et agrandi par Constantin, pouvait accueillir 100 000 spectateurs. Les factions des Bleus et des Verts y étaient des partis politiques autant que sportifs. La révolte de Nika (532) y fit 30 000 morts.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quelle dispute théologique du IXe siècle divisa l''Église entre Rome et Constantinople, aboutissant au Grand Schisme de 1054 ?',
 'Sur la nature du Saint-Esprit et l''autorité du Pape, les deux Rome ne purent s''accorder — et la chrétienté se brisa en deux.',
 '["La querelle du Filioque", "La querelle des investitures", "L''iconoclasme", "L''arianisme"]',
 'La querelle du Filioque',
 'Le Filioque ("et du Fils") est l''ajout fait par l''Église latine au Credo : le Saint-Esprit procède du Père "et du Fils". Constantinople refusait cet ajout. Cette divergence théologique, combinée à des rivalités politiques, mena au Grand Schisme de 1054 séparant catholicisme et orthodoxie.',
 true),

('daily', 'easy', 'faction-byzantine', 'qcm',
 'Quel Empereuromain byzantin du XIe siècle fit appel au pape Urbain II, déclenchant indirectement la Première Croisade ?',
 'Il demandait des mercenaires — et reçut à la place des armées de pèlerins armés qui traversèrent son Empire comme un fleuve en crue.',
 '["Alexis Ier Comnène", "Basile II", "Romain IV Diogène", "Jean II Comnène"]',
 'Alexis Ier Comnène',
 'En 1095, l''Empereuromain byzantin Alexis Ier Comnène envoya des ambassadeurs au Concile de Plaisance pour demander des mercenaires contre les Turcs Seldjoukides. Le Pape Urbain II lança à la place la Première Croisade au Concile de Clermont, dépassant largement les attentes d''Alexis.',
 true);
